baseURL = 'https://agres.online/'
languageCode = 'en-us'
title = 'agres.online'

[params]
    name = "Dominik Agre≈°"
    email = "dominik@agres.online"
    browserTitle = "agres"
    greeting = "Welcome"

    [[params.socials]]
    name = "github"
    url = "https://github.com/agresdominik"

    [[params.socials]]
    name = "linkedin"
    url = "https://linkedin.com/in/dominik-agres"

    [[params.socials]]
    name = "email"
    url = "mailto:dominik@agres.online"

    [[params.socials]]
    name = "pgp"
    url = "/publickey.asc"

    [[params.info]]
    name = "Impressum"
    url = "/impressim"

    [[params.info]]
    name = "Datenschutz"
    url = "/datenschutz"

    [[params.info]]
    name = "Email"
    url = "mailto:dominik@agres.online"

    [[params.info]]
    name = "PGP-Key"
    url = "/publickey.asc"

    [[params.info]]
    name = "RSS"
    url = "/blog/index.xml"

[markup.goldmark.renderer]
    unsafe = true

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = false
        lineNos = false
        lineNumbersInTable = true
        noClasses = false
        style = "dracula"
    [markup.goldmark]
        [markup.goldmark.extensions]
          footnote = true

[languages]
    [languages.de]
    languageCode = 'de-DE'
    languageName = 'Deutsch'
    weight = 2
    [languages.de.params]
        reading_speed = 179
    [languages.en]
    languageCode = 'en-US'
    languageName = 'English'
    weight = 1
    [languages.en.params]
        reading_speed = 228

[outputs]
    home = ["HTML"]
    section = ["HTML", "RSS"]
